#!/bin/sh

LeaseFile=/tmp/dhcp.leases
TmpFile=/tmp/hackers
StateFile=/tmp/hackers.md5
Hash=md5sum

awk '{ if ($1 > '$(date +%s)') print $2 }' < $LeaseFile > $TmpFile
OldHash=$(cat $StateFile 2>/dev/null)
NewHash=$($Hash $TmpFile | cut -f1 -d" ")
if [ "$OldHash" != "$NewHash" ]; then
	# send new state, update local state only if transmission was succesful
	(	echo Es sind $(wc -l <$TmpFile) Hacker im Space:
		cat $TmpFile) \
	|  nc -c feinsterfug.de 666 \
	&& echo "$NewHash" > $StateFile
fi
